global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'authservice'
    static_configs:
      - targets: ['authservice:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'benefitservice'
    static_configs:
      - targets: ['benefitservice:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'employeeservice'
    static_configs:
      - targets: ['employeeservice:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s